### ISSUE TITLE
Cloud you give me the admin access on this repo ;-)

### ISSUE THREAD

**Issue by Remiii** [gotakk/ViewModelBundle#4]

**Comment by gotakk** [comment]
Hmm I searched but it seems to be impossible with a personal account. It possible only on a organization account.
http://stackoverflow.com/questions/16250301/how-to-manage-collaborator-rights-in-github
http://stackoverflow.com/questions/5010754/github-collaborators-have-commit-access

**Comment by Remiii** [comment]
@gotakk :crying_cat_face:
